name: sta_cli
description: STA CLI - Flutter project scaffolding tool
version: 1.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  path: ^1.9.0
  yaml: ^3.1.2
  ansicolor: ^2.0.2

dev_dependencies:
  lints: ^6.1.0

executables:
  sta: main
