name: sta_cli
description: A powerful CLI tool to scaffold Flutter projects with clean MVC architecture, GetX state management, and pre-configured networking, auth flow, and UI components.
version: 0.1.6
homepage: https://github.com/mdnahidhossen1911/sta_cli


environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  path: ^1.9.0
  yaml: ^3.1.2
  ansicolor: ^2.0.2

dev_dependencies:
  lints: ^6.1.0

executables:
  sta:

repository: https://github.com/mdnahidhossen1911/sta_cli
issue_tracker: https://github.com/mdnahidhossen1911/sta_cli/issues
